### ISSUE TITLE
Create chromeOS docker container

### ISSUE THREAD

**Issue by Brunux** [Brunux/chromebrew#1]
Simple docker container of the chromeOS for cloud deployment, useful for the continuous integration

**Comment by jayvdb** [comment]
Is this it? https://hub.docker.com/r/brunux/chromeos/ ;-)

Any chance you could put that Dockerfile in a GitHub repo , so it can be maintained ?

**Comment by Brunux** [comment]
Yes it is, the image was extracted directly from the a fresh install of ChromeOS then pushed to an empty docker image, there is no `Dockerfile` since the files were pushed directly.

**Comment by jayvdb** [comment]
It appears to be one of the only (published) chromeOS docker containers.  @jam7 has also done some cross-compiler work.

I tried to use it for https://github.com/skycocker/chromebrew/issues/3353 , and ran into a bug, it seems in chromebrew.

I noticed that cpkg also doesnt have CI, and many of @GalliumOS repos also dont have CI.

**Comment by jayvdb** [comment]
I got it working https://github.com/skycocker/chromebrew/pull/3367 .  Thanks so much.
